### PR TITLE
Scripts for Chapter 5: Basic Page Management

### PR DESCRIPTION
**Pull request by agentolivia**
This is a video script for this tutorial: https://www.drupal.org/docs/user_guide/en/content-create.html

### CODE REVIEW

**Comment by agentolivia** [comment]
I added some commentary about the CKEditor toolbar since there are no other lessons in the guide about that.

**Comment by agentolivia** [comment]
All the scripts for Chapter 5 have been added to this PR.

**Comment by eojthebrave** [comment]
Same as the other PR. I think we should merge this into video/scripts instead of 8.x-3.x for now.

**Comment by agentolivia** [comment]
I updated the base branch to videos/scripts.

**Pull request merged**
