### PR TITLE
Updating asset and YouTube URLs for User Guide videos

### PR DESCRIPTION
**Pull request by agentolivia**
Updated asset ID and youtube URL for:
- Updating a Theme
- Downloading and Installing a Theme from drupal.org
- Downloading and Installing a Module from drupal.org
- Updating the Core Software
- Updating a Module

### CODE REVIEW

**Review by eojthebrave — APPROVED** [review]
Looks good to me. @agentolivia should we also delete the now un-used assets from d.me when this gets merged?

**Comment by agentolivia** [comment]
Yes, that's a good idea.

A todo for me:

Delete the following assets: 1584, 1586, 1566, 1557, 1565.

Trello card: https://trello.com/c/EeddT0cS

**Comment by agentolivia** [comment]
Ugh this never got merged.

**Comment by agentolivia** [comment]
@eojthebrave How do I get the videos updated on our site?

**Comment by eojthebrave** [comment]
@agentolivia I believe they should update via the import script as long as the .csv file is updated. Which this PR does. But ... that doesn't appear to be working ... I'll try and dig into it this morning.

**Comment by eojthebrave** [comment]
Okay. I think I've got this sorted out now. Example https://drupalize.me/tutorial/user-guide/extend-module-install?p=3072, now uses video 1631, instead of 1584.

The issue was that the CI job which uses rsync to transfer the CSV file to Pantheon had a `--size-only` flag for the rsync command. Which means skip the file if the size hasn't changed. In this case, the size isn't changing because you're replacing, but not adding/removing, any content. I removed that flag and ran the job again and it looks like they're updated.

**Comment by agentolivia** [comment]
Thank you!

**Pull request merged**
